FEATURES   ?= claude,gitbutler,opencode,pnpm
BASE_IMAGE ?= mcr.microsoft.com/devcontainers/typescript-node:24-trixie

.PHONY: help test test-auto test-scenarios test-global

help:
	@echo "Targets:"
	@echo "  test            auto + scenario + global tests"
	@echo "  test-auto       autogenerated tests"
	@echo "  test-scenarios  scenario tests"
	@echo "  test-global     global scenario tests"
	@echo ""
	@echo "Vars:"
	@echo "  FEATURES='$(FEATURES)'  (comma-separated; e.g. FEATURES=claude)"
	@echo "  BASE_IMAGE='$(BASE_IMAGE)'"

test: test-auto test-scenarios test-global

test-auto:
	devcontainer features test \
		--features "$(FEATURES)" \
		--base-image "$(BASE_IMAGE)" \
		--skip-scenarios \
		--project-folder .

test-scenarios:
	devcontainer features test \
		--features "$(FEATURES)" \
		--skip-autogenerated \
		--project-folder .

test-global:
	devcontainer features test \
		--global-scenarios-only \
		--project-folder .
