FEATURES     ?= claude,gitbutler,opencode,rtk
BASE_IMAGE   ?= mcr.microsoft.com/devcontainers/typescript-node:24-trixie
BASE_PATH    ?= ./src
OCI_REGISTRY ?= ghcr.io
NAMESPACE    ?=

.PHONY: help test test-auto test-scenarios test-global docs

help:
	@echo "Targets:"
	@echo "  test            auto + scenario + global tests"
	@echo "  test-auto       autogenerated tests"
	@echo "  test-scenarios  scenario tests"
	@echo "  test-global     global scenario tests"
	@echo "  docs            generate per-feature README.md (mirrors devcontainers/action)"
	@echo ""
	@echo "Vars:"
	@echo "  FEATURES='$(FEATURES)'  (comma-separated; e.g. FEATURES=claude)"
	@echo "  BASE_IMAGE='$(BASE_IMAGE)'"
	@echo "  BASE_PATH='$(BASE_PATH)'"
	@echo "  OCI_REGISTRY='$(OCI_REGISTRY)'"
	@echo "  NAMESPACE='$(NAMESPACE)' (default: derived from git remote)"

test: test-auto test-scenarios test-global

test-auto:
	devcontainer features test \
		--features "$(FEATURES)" \
		--base-image "$(BASE_IMAGE)" \
		--skip-scenarios \
		--project-folder .

test-scenarios:
	devcontainer features test \
		--features "$(FEATURES)" \
		--skip-autogenerated \
		--project-folder .

test-global:
	devcontainer features test \
		--global-scenarios-only \
		--project-folder .

docs:
	./scripts/generate-docs.sh "$(BASE_PATH)" "$(OCI_REGISTRY)" "$(NAMESPACE)"
