name: "Release features"

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  publish:
    name: "Publish to GHCR"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: "Publish features"
        uses: devcontainers/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          oci-registry: "ghcr.io"
          features-namespace: "synergy-shock/devcontainer-features"
